variables:
    GIT_STRATEGY: clone

stages:
  - deploy

deploy checks codes to shared reframe directory:
  stage: deploy
  tags:
    - shell.login3.pi.sjtu.edu.cn
  only:
    - master
    - merge_request
  before_script:
    - git clone https://github.com/eth-cscs/reframe.git
  script:
    - mv sjtuhpc-checks reframe/
    - cp config/sjtupi2.py reframe/config && ln -s config/sjtupi2.py  reframe/settings.py
    - sudo rsync -avr --progress reframe /lustre/share/tmp/

deploy jobs samples to a shared directory:
  stage: deploy
  tags:
    - shell.login3.pi.sjtu.edu.cn
  only:
    - master
    - merge_request
  script:
    - for d in `ls sjtuhpc-checks/apps`; do sudo rsync -avr --progress --delete sjtuhpc-checks/apps/$d/ /lustre/share/samples/$d/; done
    - for d in `ls sjtuhpc-checks/benchmarks`; do sudo rsync -avr --progress --delete sjtuhpc-checks/benchmarks/$d/ /lustre/share/samples/$d/; done
